// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1hZDfvGDXBEM9j7FAwLJB1K5F3vdzBUQ',
    appId: '1:314827363894:web:141de15cda59706bf5aa97',
    messagingSenderId: '314827363894',
    projectId: 'my-product-app3914',
    authDomain: 'my-product-app3914.firebaseapp.com',
    storageBucket: 'my-product-app3914.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXzCOUJhojv0ls4xvvQoJsx4g5Bo6I6LE',
    appId: '1:314827363894:android:9a22e749831dec19f5aa97',
    messagingSenderId: '314827363894',
    projectId: 'my-product-app3914',
    storageBucket: 'my-product-app3914.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvS97GQ-nEeBZF0v10m_SxMomLkQc5m5U',
    appId: '1:314827363894:ios:1c512a756a52a0bef5aa97',
    messagingSenderId: '314827363894',
    projectId: 'my-product-app3914',
    storageBucket: 'my-product-app3914.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvS97GQ-nEeBZF0v10m_SxMomLkQc5m5U',
    appId: '1:314827363894:ios:1c512a756a52a0bef5aa97',
    messagingSenderId: '314827363894',
    projectId: 'my-product-app3914',
    storageBucket: 'my-product-app3914.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1hZDfvGDXBEM9j7FAwLJB1K5F3vdzBUQ',
    appId: '1:314827363894:web:f91f26fa924c1b37f5aa97',
    messagingSenderId: '314827363894',
    projectId: 'my-product-app3914',
    authDomain: 'my-product-app3914.firebaseapp.com',
    storageBucket: 'my-product-app3914.firebasestorage.app',
  );
}
